// Demo products inserted on first start when the database is empty (Thai grocery theme).
export const initialProducts = [
  {
    id: 'prod_1',
    name: 'ข้าวหอมมะลิ คัดพิเศษ (5 กก.)',
    price: 185,
    promoPrice: 165,
    category: 'ข้าวสาร/แป้ง',
    stock: 12,
    minStock: 4,
    description: 'ข้าวหอมมะลิแท้คัดพิเศษ หอม นุ่ม น่ารับประทาน หุงขึ้นหม้อ',
  },
  {
    id: 'prod_2',
    name: 'นมสดพาสเจอร์ไรส์ รสจืด Meiji (2 ลิตร)',
    price: 95,
    category: 'ของสด/นม',
    stock: 3,
    minStock: 5,
    description: 'นมโคแท้ 100% สดใหม่ แคลเซียมสูง ซ่อมแซมกระดูกและฟัน',
  },
  {
    id: 'prod_3',
    name: 'บะหมี่กึ่งสำเร็จรูป ไวไว รสปรุงสำเร็จ (แพ็ค 10)',
    price: 65,
    promoPrice: 59,
    category: 'อาหารแห้ง/กึ่งสำเร็จรูป',
    stock: 35,
    minStock: 8,
    description: 'บะหมี่เส้นเหนียวนุ่ม รสชาติเข้มข้น ถูกปากคนไทยมายาวนาน',
  },
  {
    id: 'prod_4',
    name: 'น้ำมันพืช ตราองุ่น (1 ลิตร)',
    price: 52,
    category: 'เครื่องปรุง/น้ำมัน',
    stock: 8,
    minStock: 4,
    description: 'น้ำมันถั่วเหลืองบริสุทธิ์ ผ่านกระบวนการกลั่นที่ทันสมัย ไม่มีคอเลสเตอรอล',
  },
  {
    id: 'prod_5',
    name: 'ไข่ไก่สด เบอร์ 2 (แผง 10 ฟอง)',
    price: 60,
    promoPrice: 52,
    category: 'ของสด/นม',
    stock: 15,
    minStock: 5,
    description: 'ไข่ไก่สดส่งตรงจากฟาร์ม สะอาด มั่นใจได้ในความสดใหม่ โปรตีนสูง',
  },
  {
    id: 'prod_6',
    name: 'กาแฟสำเร็จรูป 3-in-1 เบนเนตต์',
    price: 110,
    category: 'เครื่องดื่ม',
    stock: 2,
    minStock: 5,
    description: 'กาแฟปรุงสำเร็จสัญชาติอิตาลี หอม กลมกล่อม เข้มเต็มรสกาแฟแท้',
  },
  {
    id: 'prod_7',
    name: 'น้ำตาลทรายขาว มิตรผล (1 กก.)',
    price: 28,
    category: 'เครื่องปรุง/น้ำมัน',
    stock: 20,
    minStock: 5,
    description: 'น้ำตาลทรายบริสุทธิ์เกรดพรีเมียม สะอาด ละลายง่าย ไม่มีสารฟอกสี',
  },
  {
    id: 'prod_8',
    name: 'ยาบำรุงผม แพนทีน แชมพู (380 มล.)',
    price: 145,
    promoPrice: 125,
    category: 'ของใช้ส่วนประกอบ/ส่วนตัว',
    stock: 18,
    minStock: 4,
    description: 'แชมพูสูตรฟื้นบำรุงผมแห้งเสีย ให้ผมนุ่มลื่น มีน้ำหนัก สุขภาพดี',
  },
  {
    id: 'prod_9',
    name: 'สบู่อนามัย เดทตอล สูตรออริจินัล',
    price: 24,
    category: 'ของใช้ส่วนประกอบ/ส่วนตัว',
    stock: 22,
    minStock: 6,
    description: 'ช่วยปกป้องผิวจากแบคทีเรียได้อย่างมีประสิทธิภาพ สะอาด มั่นใจทุกวัน',
  },
  {
    id: 'prod_10',
    name: 'น้ำยาล้างจาน ตราซันไลต์ ถุงเติม (500 มล.)',
    price: 18,
    category: 'น้ำยา/ของใช้ในบ้าน',
    stock: 14,
    minStock: 4,
    description: 'ล้างคราบมัน คราบอาหาร ได้อย่างหมดจด ด้วยพลังเลมอนแท้',
  }
];
